apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: lf-demo
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      serviceAccountName:  lf-demo-sa
      containers:
      - name: copysecret
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "if [ -z \"$(kubectl get secret ibm-entitlement-key -n lf-demo | grep found)\" ]; \
          then kubectl get secret ibm-entitlement-key -n cp4i -o json \
          | jq -r '.metadata.namespace=\"lf-demo\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences,  .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n lf-demo -f - ;\
          else echo already_created; fi"
      restartPolicy: Never 