apiVersion: v1
kind: ServiceAccount
metadata:
  name: lf-demo-job-sa
  namespace: lf-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: lf-demo-job-sa
    namespace: lf-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin