site_name: Life Insurance Demonstration
site_author: Jerome Boyer
repo_url: https://github.com/jbcodeforce/life-insurance-demo
remote_branch: gh-pages
remote_name: origin
nav:
  - Introduction: index.md
  - Information:
    - Why EDA now?: eda.md
    - Fit for purpose: https://ibm-cloud-architecture.github.io/refarch-eda/concepts/fit-to-purpose/
    - EDA Reference Architecture: https://ibm-cloud-architecture.github.io/refarch-eda/introduction/reference-architecture/#event-driven-architecture
    - Demonstrating Event Streams: https://ibm-cloud-architecture.github.io/eda-tech-academy/demo/
  - Design: design.md
  - Demonstration: demo.md
  - OpenShift Deployment: deployment.md 


theme: 
  name: material
  # custom_dir: docs/overrides
  palette:
    scheme: default
  language: en
  include_search_page: false
  search_index_only: true
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.tabs
      - navigation.instant
      # - navigation.indexes
      - navigation.sections
      - navigation.expand
      #- navigation.tracking
      - navigation.tabs.sticky

extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - meta
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
