apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: store-mq
  namespace: lf-demo
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: QM1
    mqsc:
      - configMap:
          name: mq-mqsc-config
          items:
            -  example.mqsc
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    metrics:
      enabled: true
    route:
      enabled: true
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - name: qmgr
          env:
            - name: MQSNOAUT
              value: 'yes' 
          envFrom:
          - configMapRef:
              name: mq-config

  version: 9.2.4.0-r1
  web:
    enabled: true

