apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: eda-kconnect-cluster
  namespace: lf-demo
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: dev-kafka-bootstrap.lf-demo.svc:9092
  image: quay.io/ibmcase/eda-kconnect-cluster-image:11.0.2
  template:
    pod:
      tmpDirSizeLimit: 100Mi
      imagePullSecrets: []
      metadata:
        annotations:
          productChargedContainers: eda-kconnect-cluster-connect
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 11.0.2
          productMetric: VIRTUAL_PROCESSOR_CORE
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          cloudpakVersion: 2022.2.1
          productCloudpakRatio: "2:1"
  config:
    group.id: eda-connect-cluster
    offset.storage.topic: eda-connect-cluster-offsets
    config.storage.topic: eda-connect-cluster-configs
    status.storage.topic: eda-connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.cleanup.policy: compact
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
#  tls:
#    trustedCertificates:
#      - secretName: quickstart-cluster-ca-cert
#        certificate: ca.crt
#  authentication:
#    type: scram-sha-512
#    username: my-connect-user
#    passwordSecret:
#      secretName: my-connect-user
#      password: my-connect-password-key
